### ISSUE TITLE
[Bug] Failed to patch com.xunmeng.pinduoduo

### ISSUE THREAD

**Issue by Vision-Wong** [JingMatrix/LSPatch#24]
### Steps to reproduce/复现步骤

1. patch apk
2. 
1. 

### Expected behaviour/预期行为

patch成功生成apk

### Actual behaviour/实际行为

patch失败

### Xposed Module List/Xposed 模块列表

```Shell
API 版本
93

LSPatch 版本
0.7 (430)

框架版本
1.10.1 (7137)

系统版本
15 (API 35)

设备
Xiaomi 23127PN0CC 

系统架构
arm64-v8a
```

### LSPatch version/LSPatch 版本

0.7

### Android version/Android 版本

15

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

<details>

```
Launch patch
, Processing /data/user/0/org.lsposed.lspatch/cache/apk/拼多多_7.40.0_74000_com.xunmeng.pinduoduo_main_standalone.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/拼多多_7.40.0_74000_com.xunmeng.pinduoduo_main_standalone-430-lspatched.apk
, apk path: /data/user/0/org.lsposed.lspatch/cache/apk/拼多多_7.40.0_74000_com.xunmeng.pinduoduo_main_standalone.apk
, Parsing original apk...
, Register apk signer with default keystore...
, Original signature
3082037130820259a0030201020204796c943f300d06092a864886f70d01010b05003069310b300906035504061302434e3111300f060355040813087368616e676861693111300f060355040713087368616e676861693110300e060355040a130778756e6d656e673110300e060355040b130778756e6d656e673110300e0603550403130778756e6d656e67301e170d3135303931363033323732315a170d3430303930393033323732315a3069310b300906035504061302434e3111300f060355040813087368616e676861693111300f060355040713087368616e676861693110300e060355040a130778756e6d656e673110300e060355040b130778756e6d656e673110300e0603550403130778756e6d656e6730820122300d06092a864886f70d01010105000382010f003082010a02820101008aee5a990832ea80113e537ac4d4405320614a03657315b1b8de9cd4d2955556b49dc9851f0bb2f28f46ebb70519c4e3e81a93e44a2c613fd176dc135bc5c62d0380e16ace83960e5bbb412d79455d2ef4fdddff3aec56b138f6cdc7c1a4c798ff76cb8e276fa68735cf90e2a4f438cf526e8ae73e6a00f8a76181ae042a93b37f3858ca85b48ac49ca1c8a3b2a20667b76c6f4c442e2bfa8a12f2d37bd13218e63b396cc44baa55b2259a63965bc2516ba3880cf53851a9d362e09d985e008e45464d1415324acede64297c6d7e13d543adb67c62eabfdc527b03b715bdef78183c3bbb53201eb09f4ebaea1fe93bd64cee4c45b6a6f6e498fb0aaf95e1fb5d0203010001a321301f301d0603551d0e04160414d30b4b1dc75bd97fe9f3ca5a15a5ad050c30443d300d06092a864886f70d01010b0500038201010048f40e91cb21023d5fc9a6e3c25e93ee4ffbac75ccf338b72c64c50600b7ebb26a1f22b4d6c239afccd1ffdd31d43b5c62eba70d092f3cd0b62f533691a73eb0a4e56d071cd56b5bf3a9b42ddaa2fb2e5bc1a38cb8ceb00186b5b3313115183f579586b58e9eec9f6ce2bdff077dda8faeda7cb037af633504be9809bb84a3908bf93d61226ef1aa823e2a6dd1c4465a6251044054182221078d604f6b0f99ce9b4d5dcb4eea747b33cc62047363c1caa88343eee466dd04e6f3d9e140961facc11b842ef5abe71d45f806421e8677e9aaf17383f12875a2d6bf7c363acab265408615b6332e24a10323266b125f1249741efdfe6f610b515b4df72a2f99c3e7
, Failed to parse AndroidManifest.xml
, D3.a: Failed to parse AndroidManifest.xml
	at u4.b.a(Unknown Source:1352)
	at c4.c.m(Unknown Source:23)
	at y3.a.k(Unknown Source:5)
	at O3.A.run(Unknown Source:111)
	at com.google.common.util.concurrent.g.run(Unknown Source:152)
	at V3.j.run(Unknown Source:2)
	at V3.a.run(Unknown Source:91)


```
</details>

**Comment by JingMatrix** [comment]
Bug confirmed, reproduced log is
```
Processing /home/jing/Downloads/com.xunmeng.pinduoduo_7.43.0.apk -> /home/jing/Downloads/./com.xunmeng.pinduoduo_7.43.0-55-lspatched.apk
Parsing original apk...
Register apk signer with default keystore...
org.lsposed.patch.LSPatch$PatchError: Failed to parse AndroidManifest.xml
	at org.lsposed.patch.LSPatch.patch(LSPatch.java:231)
	at org.lsposed.patch.LSPatch.doCommandLine(LSPatch.java:169)
	at org.lsposed.patch.LSPatch.main(LSPatch.java:144)
```
