### ISSUE TITLE
[Bug] error with launch Apk

### ISSUE THREAD

**Issue by Alcatcut** [JingMatrix/LSPatch#5]
### Steps to reproduce/复现步骤

1. Launch patch
, Processing /data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched-398-lspatched.apk
, apk path: /data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched.apk
, Parsing original apk...
, Failed to read zip file '/data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched.apk'.
, java.io.IOException: Failed to read zip file '/data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched.apk'.
	at y4.y.<init>(Unknown Source:223)
	at y4.t.<init>(Unknown Source:6)
	at a9.a.a(Unknown Source:325)
	at h8.b.g(Unknown Source:23)
	at k7.a.u(Unknown Source:5)
	at z7.e0.run(Unknown Source:109)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(Unknown Source:76)
Caused by: java.io.IOException: Cannot read entry 'assets/lspatch/origin.apk' (offset: 1723, size: 127393582) because it overlaps with 'META-INF/androidx.dynamicanimation_dynamicanimation.version' (offset: 11786, size: 96)
	at y4.y.P(Unknown Source:868)
	at y4.y.<init>(Unknown Source:155)
	... 8 more

1. 
1. 

### Expected behaviour/预期行为

Launch patch
, Processing /data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched-398-lspatched.apk
, apk path: /data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched.apk
, Parsing original apk...
, Failed to read zip file '/data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched.apk'.
, java.io.IOException: Failed to read zip file '/data/user/0/org.lsposed.lspatch/cache/apk/base-398-lspatched.apk'.
	at y4.y.<init>(Unknown Source:223)
	at y4.t.<init>(Unknown Source:6)
	at a9.a.a(Unknown Source:325)
	at h8.b.g(Unknown Source:23)
	at k7.a.u(Unknown Source:5)
	at z7.e0.run(Unknown Source:109)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(Unknown Source:76)
Caused by: java.io.IOException: Cannot read entry 'assets/lspatch/origin.apk' (offset: 1723, size: 127393582) because it overlaps with 'META-INF/androidx.dynamicanimation_dynamicanimation.version' (offset: 11786, size: 96)
	at y4.y.P(Unknown Source:868)
	at y4.y.<init>(Unknown Source:155)
	... 8 more

### Actual behaviour/实际行为

Errors.. Not working 

### Xposed Module List/Xposed 模块列表

```Shell
As in website
```

### LSPatch version/LSPatch 版本

Last version 

### Android version/Android 版本

Xiaomi hyberOS

### Shizuku version/Shizuku 版本

Last version 

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Apk file/Apk 文件

Apk

### Logs/日志

<details>

```.           J
# Replace this line with the log / 将此行用日志替换
```
</details>

**Comment by JingMatrix** [comment]
Don't use LSPatch for APK files that are already patched.
Please always patch **untouched** APKs.
